// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/Trailer.proto

package org.inlighting.proto;

public final class TrailerProtos {
  private TrailerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrailerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.inlighting.proto.Trailer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string mergedFile = 1;</code>
     * @return Whether the mergedFile field is set.
     */
    boolean hasMergedFile();
    /**
     * <code>required string mergedFile = 1;</code>
     * @return The mergedFile.
     */
    java.lang.String getMergedFile();
    /**
     * <code>required string mergedFile = 1;</code>
     * @return The bytes for mergedFile.
     */
    com.google.protobuf.ByteString
        getMergedFileBytes();

    /**
     * <code>required uint32 kvsLength = 2;</code>
     * @return Whether the kvsLength field is set.
     */
    boolean hasKvsLength();
    /**
     * <code>required uint32 kvsLength = 2;</code>
     * @return The kvsLength.
     */
    int getKvsLength();

    /**
     * <code>required string minKey = 3;</code>
     * @return Whether the minKey field is set.
     */
    boolean hasMinKey();
    /**
     * <code>required string minKey = 3;</code>
     * @return The minKey.
     */
    java.lang.String getMinKey();
    /**
     * <code>required string minKey = 3;</code>
     * @return The bytes for minKey.
     */
    com.google.protobuf.ByteString
        getMinKeyBytes();

    /**
     * <code>required string maxKey = 4;</code>
     * @return Whether the maxKey field is set.
     */
    boolean hasMaxKey();
    /**
     * <code>required string maxKey = 4;</code>
     * @return The maxKey.
     */
    java.lang.String getMaxKey();
    /**
     * <code>required string maxKey = 4;</code>
     * @return The bytes for maxKey.
     */
    com.google.protobuf.ByteString
        getMaxKeyBytes();

    /**
     * <code>required uint32 bloomFilterLength = 5;</code>
     * @return Whether the bloomFilterLength field is set.
     */
    boolean hasBloomFilterLength();
    /**
     * <code>required uint32 bloomFilterLength = 5;</code>
     * @return The bloomFilterLength.
     */
    int getBloomFilterLength();
  }
  /**
   * Protobuf type {@code org.inlighting.proto.Trailer}
   */
  public static final class Trailer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.inlighting.proto.Trailer)
      TrailerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trailer.newBuilder() to construct.
    private Trailer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trailer() {
      mergedFile_ = "";
      minKey_ = "";
      maxKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Trailer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trailer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              mergedFile_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              kvsLength_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              minKey_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              maxKey_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              bloomFilterLength_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.inlighting.proto.TrailerProtos.internal_static_org_inlighting_proto_Trailer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.inlighting.proto.TrailerProtos.internal_static_org_inlighting_proto_Trailer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.inlighting.proto.TrailerProtos.Trailer.class, org.inlighting.proto.TrailerProtos.Trailer.Builder.class);
    }

    private int bitField0_;
    public static final int MERGEDFILE_FIELD_NUMBER = 1;
    private volatile java.lang.Object mergedFile_;
    /**
     * <code>required string mergedFile = 1;</code>
     * @return Whether the mergedFile field is set.
     */
    @java.lang.Override
    public boolean hasMergedFile() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string mergedFile = 1;</code>
     * @return The mergedFile.
     */
    @java.lang.Override
    public java.lang.String getMergedFile() {
      java.lang.Object ref = mergedFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mergedFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mergedFile = 1;</code>
     * @return The bytes for mergedFile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMergedFileBytes() {
      java.lang.Object ref = mergedFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mergedFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KVSLENGTH_FIELD_NUMBER = 2;
    private int kvsLength_;
    /**
     * <code>required uint32 kvsLength = 2;</code>
     * @return Whether the kvsLength field is set.
     */
    @java.lang.Override
    public boolean hasKvsLength() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required uint32 kvsLength = 2;</code>
     * @return The kvsLength.
     */
    @java.lang.Override
    public int getKvsLength() {
      return kvsLength_;
    }

    public static final int MINKEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object minKey_;
    /**
     * <code>required string minKey = 3;</code>
     * @return Whether the minKey field is set.
     */
    @java.lang.Override
    public boolean hasMinKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string minKey = 3;</code>
     * @return The minKey.
     */
    @java.lang.Override
    public java.lang.String getMinKey() {
      java.lang.Object ref = minKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          minKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string minKey = 3;</code>
     * @return The bytes for minKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMinKeyBytes() {
      java.lang.Object ref = minKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAXKEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object maxKey_;
    /**
     * <code>required string maxKey = 4;</code>
     * @return Whether the maxKey field is set.
     */
    @java.lang.Override
    public boolean hasMaxKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string maxKey = 4;</code>
     * @return The maxKey.
     */
    @java.lang.Override
    public java.lang.String getMaxKey() {
      java.lang.Object ref = maxKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          maxKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string maxKey = 4;</code>
     * @return The bytes for maxKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMaxKeyBytes() {
      java.lang.Object ref = maxKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maxKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOOMFILTERLENGTH_FIELD_NUMBER = 5;
    private int bloomFilterLength_;
    /**
     * <code>required uint32 bloomFilterLength = 5;</code>
     * @return Whether the bloomFilterLength field is set.
     */
    @java.lang.Override
    public boolean hasBloomFilterLength() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required uint32 bloomFilterLength = 5;</code>
     * @return The bloomFilterLength.
     */
    @java.lang.Override
    public int getBloomFilterLength() {
      return bloomFilterLength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMergedFile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKvsLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBloomFilterLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mergedFile_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, kvsLength_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, minKey_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, maxKey_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, bloomFilterLength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mergedFile_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, kvsLength_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, minKey_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, maxKey_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, bloomFilterLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.inlighting.proto.TrailerProtos.Trailer)) {
        return super.equals(obj);
      }
      org.inlighting.proto.TrailerProtos.Trailer other = (org.inlighting.proto.TrailerProtos.Trailer) obj;

      if (hasMergedFile() != other.hasMergedFile()) return false;
      if (hasMergedFile()) {
        if (!getMergedFile()
            .equals(other.getMergedFile())) return false;
      }
      if (hasKvsLength() != other.hasKvsLength()) return false;
      if (hasKvsLength()) {
        if (getKvsLength()
            != other.getKvsLength()) return false;
      }
      if (hasMinKey() != other.hasMinKey()) return false;
      if (hasMinKey()) {
        if (!getMinKey()
            .equals(other.getMinKey())) return false;
      }
      if (hasMaxKey() != other.hasMaxKey()) return false;
      if (hasMaxKey()) {
        if (!getMaxKey()
            .equals(other.getMaxKey())) return false;
      }
      if (hasBloomFilterLength() != other.hasBloomFilterLength()) return false;
      if (hasBloomFilterLength()) {
        if (getBloomFilterLength()
            != other.getBloomFilterLength()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMergedFile()) {
        hash = (37 * hash) + MERGEDFILE_FIELD_NUMBER;
        hash = (53 * hash) + getMergedFile().hashCode();
      }
      if (hasKvsLength()) {
        hash = (37 * hash) + KVSLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getKvsLength();
      }
      if (hasMinKey()) {
        hash = (37 * hash) + MINKEY_FIELD_NUMBER;
        hash = (53 * hash) + getMinKey().hashCode();
      }
      if (hasMaxKey()) {
        hash = (37 * hash) + MAXKEY_FIELD_NUMBER;
        hash = (53 * hash) + getMaxKey().hashCode();
      }
      if (hasBloomFilterLength()) {
        hash = (37 * hash) + BLOOMFILTERLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getBloomFilterLength();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.inlighting.proto.TrailerProtos.Trailer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.inlighting.proto.TrailerProtos.Trailer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.inlighting.proto.Trailer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.inlighting.proto.Trailer)
        org.inlighting.proto.TrailerProtos.TrailerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.inlighting.proto.TrailerProtos.internal_static_org_inlighting_proto_Trailer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.inlighting.proto.TrailerProtos.internal_static_org_inlighting_proto_Trailer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.inlighting.proto.TrailerProtos.Trailer.class, org.inlighting.proto.TrailerProtos.Trailer.Builder.class);
      }

      // Construct using org.inlighting.proto.TrailerProtos.Trailer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mergedFile_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        kvsLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        minKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        maxKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        bloomFilterLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.inlighting.proto.TrailerProtos.internal_static_org_inlighting_proto_Trailer_descriptor;
      }

      @java.lang.Override
      public org.inlighting.proto.TrailerProtos.Trailer getDefaultInstanceForType() {
        return org.inlighting.proto.TrailerProtos.Trailer.getDefaultInstance();
      }

      @java.lang.Override
      public org.inlighting.proto.TrailerProtos.Trailer build() {
        org.inlighting.proto.TrailerProtos.Trailer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.inlighting.proto.TrailerProtos.Trailer buildPartial() {
        org.inlighting.proto.TrailerProtos.Trailer result = new org.inlighting.proto.TrailerProtos.Trailer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mergedFile_ = mergedFile_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.kvsLength_ = kvsLength_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.minKey_ = minKey_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxKey_ = maxKey_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.bloomFilterLength_ = bloomFilterLength_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.inlighting.proto.TrailerProtos.Trailer) {
          return mergeFrom((org.inlighting.proto.TrailerProtos.Trailer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.inlighting.proto.TrailerProtos.Trailer other) {
        if (other == org.inlighting.proto.TrailerProtos.Trailer.getDefaultInstance()) return this;
        if (other.hasMergedFile()) {
          bitField0_ |= 0x00000001;
          mergedFile_ = other.mergedFile_;
          onChanged();
        }
        if (other.hasKvsLength()) {
          setKvsLength(other.getKvsLength());
        }
        if (other.hasMinKey()) {
          bitField0_ |= 0x00000004;
          minKey_ = other.minKey_;
          onChanged();
        }
        if (other.hasMaxKey()) {
          bitField0_ |= 0x00000008;
          maxKey_ = other.maxKey_;
          onChanged();
        }
        if (other.hasBloomFilterLength()) {
          setBloomFilterLength(other.getBloomFilterLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMergedFile()) {
          return false;
        }
        if (!hasKvsLength()) {
          return false;
        }
        if (!hasMinKey()) {
          return false;
        }
        if (!hasMaxKey()) {
          return false;
        }
        if (!hasBloomFilterLength()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.inlighting.proto.TrailerProtos.Trailer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.inlighting.proto.TrailerProtos.Trailer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object mergedFile_ = "";
      /**
       * <code>required string mergedFile = 1;</code>
       * @return Whether the mergedFile field is set.
       */
      public boolean hasMergedFile() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string mergedFile = 1;</code>
       * @return The mergedFile.
       */
      public java.lang.String getMergedFile() {
        java.lang.Object ref = mergedFile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mergedFile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mergedFile = 1;</code>
       * @return The bytes for mergedFile.
       */
      public com.google.protobuf.ByteString
          getMergedFileBytes() {
        java.lang.Object ref = mergedFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mergedFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mergedFile = 1;</code>
       * @param value The mergedFile to set.
       * @return This builder for chaining.
       */
      public Builder setMergedFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mergedFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mergedFile = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMergedFile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mergedFile_ = getDefaultInstance().getMergedFile();
        onChanged();
        return this;
      }
      /**
       * <code>required string mergedFile = 1;</code>
       * @param value The bytes for mergedFile to set.
       * @return This builder for chaining.
       */
      public Builder setMergedFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mergedFile_ = value;
        onChanged();
        return this;
      }

      private int kvsLength_ ;
      /**
       * <code>required uint32 kvsLength = 2;</code>
       * @return Whether the kvsLength field is set.
       */
      @java.lang.Override
      public boolean hasKvsLength() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required uint32 kvsLength = 2;</code>
       * @return The kvsLength.
       */
      @java.lang.Override
      public int getKvsLength() {
        return kvsLength_;
      }
      /**
       * <code>required uint32 kvsLength = 2;</code>
       * @param value The kvsLength to set.
       * @return This builder for chaining.
       */
      public Builder setKvsLength(int value) {
        bitField0_ |= 0x00000002;
        kvsLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 kvsLength = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKvsLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        kvsLength_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object minKey_ = "";
      /**
       * <code>required string minKey = 3;</code>
       * @return Whether the minKey field is set.
       */
      public boolean hasMinKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string minKey = 3;</code>
       * @return The minKey.
       */
      public java.lang.String getMinKey() {
        java.lang.Object ref = minKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            minKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string minKey = 3;</code>
       * @return The bytes for minKey.
       */
      public com.google.protobuf.ByteString
          getMinKeyBytes() {
        java.lang.Object ref = minKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          minKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string minKey = 3;</code>
       * @param value The minKey to set.
       * @return This builder for chaining.
       */
      public Builder setMinKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        minKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string minKey = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minKey_ = getDefaultInstance().getMinKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string minKey = 3;</code>
       * @param value The bytes for minKey to set.
       * @return This builder for chaining.
       */
      public Builder setMinKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        minKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object maxKey_ = "";
      /**
       * <code>required string maxKey = 4;</code>
       * @return Whether the maxKey field is set.
       */
      public boolean hasMaxKey() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string maxKey = 4;</code>
       * @return The maxKey.
       */
      public java.lang.String getMaxKey() {
        java.lang.Object ref = maxKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            maxKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string maxKey = 4;</code>
       * @return The bytes for maxKey.
       */
      public com.google.protobuf.ByteString
          getMaxKeyBytes() {
        java.lang.Object ref = maxKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          maxKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string maxKey = 4;</code>
       * @param value The maxKey to set.
       * @return This builder for chaining.
       */
      public Builder setMaxKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        maxKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string maxKey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxKey_ = getDefaultInstance().getMaxKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string maxKey = 4;</code>
       * @param value The bytes for maxKey to set.
       * @return This builder for chaining.
       */
      public Builder setMaxKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        maxKey_ = value;
        onChanged();
        return this;
      }

      private int bloomFilterLength_ ;
      /**
       * <code>required uint32 bloomFilterLength = 5;</code>
       * @return Whether the bloomFilterLength field is set.
       */
      @java.lang.Override
      public boolean hasBloomFilterLength() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required uint32 bloomFilterLength = 5;</code>
       * @return The bloomFilterLength.
       */
      @java.lang.Override
      public int getBloomFilterLength() {
        return bloomFilterLength_;
      }
      /**
       * <code>required uint32 bloomFilterLength = 5;</code>
       * @param value The bloomFilterLength to set.
       * @return This builder for chaining.
       */
      public Builder setBloomFilterLength(int value) {
        bitField0_ |= 0x00000010;
        bloomFilterLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 bloomFilterLength = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBloomFilterLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bloomFilterLength_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.inlighting.proto.Trailer)
    }

    // @@protoc_insertion_point(class_scope:org.inlighting.proto.Trailer)
    private static final org.inlighting.proto.TrailerProtos.Trailer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.inlighting.proto.TrailerProtos.Trailer();
    }

    public static org.inlighting.proto.TrailerProtos.Trailer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Trailer>
        PARSER = new com.google.protobuf.AbstractParser<Trailer>() {
      @java.lang.Override
      public Trailer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trailer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trailer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trailer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.inlighting.proto.TrailerProtos.Trailer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_inlighting_proto_Trailer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_inlighting_proto_Trailer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/resources/protobuf/Trailer.pr" +
      "oto\022\024org.inlighting.proto\"k\n\007Trailer\022\022\n\n" +
      "mergedFile\030\001 \002(\t\022\021\n\tkvsLength\030\002 \002(\r\022\016\n\006m" +
      "inKey\030\003 \002(\t\022\016\n\006maxKey\030\004 \002(\t\022\031\n\021bloomFilt" +
      "erLength\030\005 \002(\rB(\n\024org.inlighting.protoB\r" +
      "TrailerProtos\240\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_inlighting_proto_Trailer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_inlighting_proto_Trailer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_inlighting_proto_Trailer_descriptor,
        new java.lang.String[] { "MergedFile", "KvsLength", "MinKey", "MaxKey", "BloomFilterLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
